### ISSUE TITLE
torrent cat

### ISSUE THREAD

**Issue by onny** [animeshkundu/torrent-dl#1]
Hey thanks for your interesting software.
I'm looking for something similair. A program that is able to "stream" a torrent file/magnet link like the linux tool "cat".
Something like:
torrent-cat [magnetlink] > myfile.iso

Do you know something like this or do you have something like this?

**Comment by animeshkundu** [comment]
Could you try using 
`torrent-dl --serve false [magnet link]`

You could combine it with the --download flag for specifying the folder to download it to
